# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [16]
        os: [ubuntu-latest]

    steps:
    - name: Checkout Git Source
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm i

    - name: Continuous Integration
      run: npm run ci
      env:
        OSS_CNPM_BUCKET: ${{ secrets.OSS_CNPM_BUCKET }}
        OSS_CNPM_BUCKET2: ${{ secrets.OSS_CNPM_BUCKET2 }}
        OSS_CNPM_ID: ${{ secrets.OSS_CNPM_ID }}
        OSS_CNPM_SECRET: ${{ secrets.OSS_CNPM_SECRET }}

    - name: Code Coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
